-   id: html-validate
    name: html-validate
    description: 'Offline HTML5 validator. Validates either a full document or a smaller (incomplete) template'
    entry: html-validate
    language: node
    'types_or': [html, javascript, jinja]
    args: []
    require_serial: false
    additional_dependencies: ["html-validate@2.3.0"]
    minimum_pre_commit_version: '2.9.2'
